# Generated by Django 4.2.2 on 2023-06-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldssapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='from_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='to_date',
            field=models.CharField(max_length=20),
        ),
    ]
